export const resumeList = [
  {
    tagline: "Hello, I'm @dowatugkins",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @1",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/Octocat.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @2",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @3",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @4",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @5",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @6",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @7",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @8",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @9",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @10",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @11",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @12",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @13",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @14",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @15",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @16",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @17",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @18",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
  {
    tagline: "Hello, I'm @19",
    image: require('../assets/images/Octocat.png'),
    byline: "Mobile Architect, entrepreneur, creator of 4 mini-me terrors, and founder of Tyrsoft.",
    date: new Date(),
    footer: {
      title: 'Also known as Doug Watkins',
      leftText: "I've been writing code for 2 decades now, and been making mobile apps for 7 of those years. \nI live in central Utah and love to build mobile apps, solve problems, and spend time with my family.",
      rightText: "I'm not currently looking for employment, but that doesn't mean I'm not interested in working with you. Hit me up if any of these pique your interest:",
      image: require('../assets/images/borderlands.png'),
      list: [
        'Consultations on Archtecture',
        'Mobile app development or planning',
        'Making your app more intuitive',
        'Playing Borderlands',
      ],
    },
  },
];
